import type { Locale } from '@/lib/i18n'

const englishMessages: Record<string, string> = {
  'Une erreur inattendue est survenue.': 'An unexpected error occurred.',
  'Connectez d’abord un compte Google Ads.': 'Connect a Google Ads account first.',
  'Compte client introuvable.': 'Client account not found.',
  'Objectif client enregistré.': 'Client goal saved.',
  'Identité de marque enregistrée.': 'Brand identity saved.',
  'Sélectionnez un fichier logo.': 'Select a logo file.',
  'Une adresse Better Auth vérifiée est requise.': 'A verified Better Auth email address is required.',
  'Préférences personnelles de tâches enregistrées.': 'Personal task preferences saved.',
  'Cette adresse est déjà membre ou invitée.': 'This email address is already a member or has a pending invitation.',
  'Le rôle du propriétaire ne peut être modifié que par un transfert de propriété.': 'The owner role can only be changed through an ownership transfer.',
  'Le propriétaire ne peut pas être retiré de son espace.': 'The owner cannot be removed from their workspace.',
  'Seul le propriétaire peut transférer la propriété.': 'Only the owner can transfer ownership.',
  'Ce membre est déjà propriétaire.': 'This member is already the owner.',
  'La confirmation ne correspond pas à l’identifiant de l’espace.': 'The confirmation does not match the workspace identifier.',
  'Le nouveau propriétaire doit déjà être membre actif.': 'The new owner must already be an active member.',
  'La propriété a déjà changé. Rechargez la page.': 'Ownership has already changed. Reload the page.',
  'Un draft RSA exige entre 3 et 15 titres, un par ligne.': 'An RSA draft requires 3 to 15 headlines, one per line.',
  'Un draft RSA exige entre 2 et 4 descriptions, une par ligne.': 'An RSA draft requires 2 to 4 descriptions, one per line.',
  'Chaque titre RSA est limité à 30 caractères.': 'Each RSA headline is limited to 30 characters.',
  'Chaque description RSA est limitée à 90 caractères.': 'Each RSA description is limited to 90 characters.',
  'Les titres RSA doivent être distincts.': 'RSA headlines must be unique.',
  'Les descriptions RSA doivent être distinctes.': 'RSA descriptions must be unique.',
  'Le batch atomique de réallocation est réservé au plan Agency.': 'Atomic reallocation batches require the Agency plan.',
  'Connexion Google Ads absente.': 'Google Ads connection is missing.',
  'Le budget transmis ne correspond plus à la campagne Google Ads.': 'The submitted budget no longer matches the Google Ads campaign.',
  'Un budget transmis ne correspond plus à sa campagne Google Ads.': 'A submitted budget no longer matches its Google Ads campaign.',
  'Le mot-clé ne correspond pas à la campagne transmise.': 'The keyword does not belong to the submitted campaign.',
  'L’annonce ne correspond pas à la campagne transmise.': 'The ad does not belong to the submitted campaign.',
  'Le groupe d’annonces ne correspond pas à la campagne transmise.': 'The ad group does not belong to the submitted campaign.',
  'Une annonce RSA identique existe déjà dans ce groupe d’annonces.': 'An identical RSA already exists in this ad group.',
  'Type de changement non pris en charge.': 'This change type is not supported.',
  'Changement validé par Google et ajouté aux approbations.': 'Google validated the change and it was added to approvals.',
  'Batch validé par Google et ajouté aux approbations.': 'Google validated the batch and it was added to approvals.',
  'Les batches atomiques multi-opérations sont réservés au plan Agency.': 'Atomic multi-operation batches require the Agency plan.',
  'Une proposition sélectionnée est introuvable ou n’est plus en attente.': 'A selected proposal is missing or no longer pending.',
  'Une proposition ayant déjà reçu un vote ne peut pas être regroupée.': 'A proposal that already received a vote cannot be batched.',
  'Toutes les propositions du batch doivent concerner le même client.': 'All batch proposals must target the same client.',
  'Une proposition sélectionnée a expiré.': 'A selected proposal has expired.',
  'Une proposition a changé pendant la création du batch.': 'A proposal changed while the batch was being created.',
  'Les mutations sont désactivées pour cet espace.': 'Google Ads mutations are disabled for this workspace.',
  'Cette demande a déjà été traitée.': 'This request has already been processed.',
  'L’auto-approbation est désactivée pour cet espace.': 'Self-approval is disabled for this workspace.',
  'Vous avez déjà voté sur cette demande.': 'You have already voted on this request.',
  'Cette demande a expiré.': 'This request has expired.',
  'Le compte ou sa connexion Google Ads est introuvable.': 'The account or its Google Ads connection could not be found.',
  'La ressource Google Ads a changé depuis la proposition. Une nouvelle proposition est requise.': 'The Google Ads resource changed after the proposal. Create a new proposal.',
  'L’état courant du batch est indisponible.': 'The current batch state is unavailable.',
  'Le budget courant du batch est introuvable.': 'The current batch budget could not be found.',
  'L’état courant du mot-clé est indisponible.': 'The current keyword state is unavailable.',
  'Changement appliqué et réconcilié dans Google Ads.': 'The change was applied and reconciled in Google Ads.',
  'Changement soumis à Google Ads. La réconciliation est en attente.': 'The change was submitted to Google Ads. Reconciliation is pending.',
  'Demande rejetée.': 'Request rejected.',
  'Demande d’approbation introuvable.': 'Approval request not found.',
  'Commentaire ajouté.': 'Comment added.',
  'Aucune connexion Google Ads active.': 'No active Google Ads connection.',
  'Google n’a pas confirmé la révocation du jeton.': 'Google did not confirm token revocation.',
  'Connexion Google Ads révoquée et supprimée.': 'Google Ads connection revoked and removed.',
  'Modèle de vigie inconnu.': 'Unknown monitor template.',
  'Vigie introuvable.': 'Monitor not found.',
  'Vigie activée.': 'Monitor enabled.',
  'Vigie mise en pause.': 'Monitor paused.',
  'Vigie activée. Elle sera exécutée chaque jour.': 'Monitor enabled. It will run daily.',
  'Alerte introuvable.': 'Alert not found.',
  'Alerte acquittée.': 'Alert acknowledged.',
  'Workflow de l’alerte mis à jour.': 'Alert workflow updated.',
  'Alerte source manquante.': 'Source alert is missing.',
  'Alerte source introuvable.': 'Source alert not found.',
  'Approbation source manquante.': 'Source approval is missing.',
  'Approbation source introuvable.': 'Source approval not found.',
  'Le titre de la tâche est requis.': 'Task title is required.',
  'Compte client de la tâche introuvable.': 'Task client account not found.',
  'Une tâche existe déjà pour cette source.': 'A task already exists for this source.',
  'Tâche introuvable.': 'Task not found.',
  'La date d’échéance est requise.': 'A due date is required.',
  'Tâche créée.': 'Task created.',
  'Tâche mise à jour.': 'Task updated.',
  'Rapport créé. Révélez son URL dans les cinq prochaines minutes.': 'Report created. Reveal its URL within the next five minutes.',
  'Modèle de rapport créé.': 'Report template created.',
  'Le modèle a été modifié ou désactivé. Rechargez la page avant de réessayer.': 'The template was changed or disabled. Reload the page before trying again.',
  'Nouvelle version du modèle enregistrée.': 'New template version saved.',
  'Modèle introuvable ou déjà désactivé.': 'Template not found or already disabled.',
  'Modèle désactivé. Les rapports existants conservent leur snapshot.': 'Template disabled. Existing reports keep their snapshot.',
  'Modèle de rapport introuvable.': 'Report template not found.',
  'Envoi planifié créé.': 'Scheduled delivery created.',
  'Planification introuvable.': 'Schedule not found.',
  'Un envoi est en cours. Réessayez dans quelques minutes.': 'A delivery is in progress. Try again in a few minutes.',
  'Envoi planifié activé.': 'Scheduled delivery enabled.',
  'Envoi planifié suspendu et lien révoqué.': 'Scheduled delivery paused and link revoked.',
  'Token du rapport planifié renouvelé. L’ancien lien est immédiatement invalide.': 'Scheduled report token rotated. The previous link is immediately invalid.',
  'Révoquez le domaine existant avant d’en configurer un autre.': 'Revoke the existing domain before configuring another one.',
  'Domaine enregistré. Publiez le TXT révélé avant de vérifier.': 'Domain saved. Publish the revealed TXT record before verification.',
  'Domaine introuvable.': 'Domain not found.',
  'Domaine vérifié, routé et actif pour les nouveaux liens de rapport.': 'Domain verified, routed and active for new report links.',
  'Propriété confirmée. Configurez les enregistrements indiqués puis relancez la vérification.': 'Ownership confirmed. Configure the indicated records, then verify again.',
  'Domaine retiré de Vercel et révoqué. Le domaine Yodev reste disponible.': 'Domain removed from Vercel and revoked. The Yodev domain remains available.',
  'Lien introuvable.': 'Link not found.',
  'Lien public révoqué immédiatement.': 'Public link revoked immediately.',
  'Ce rapport n’accepte pas de retours.': 'This report does not accept feedback.',
  'Rapport introuvable.': 'Report not found.',
  'Clé créée. Révélez-la une seule fois dans les cinq prochaines minutes.': 'Key created. Reveal it once within the next five minutes.',
  'Clé API introuvable.': 'API key not found.',
  'Clé API révoquée.': 'API key revoked.',
  'Sélectionnez le compte client concerné.': 'Select the relevant client account.',
  'Saisissez l’identifiant de campagne concerné.': 'Enter the relevant campaign ID.',
  'Règles de sécurité enregistrées.': 'Safety policies saved.',
  'Canal de notification ajouté.': 'Notification channel added.',
  'Canal introuvable.': 'Channel not found.',
  'Canal désactivé.': 'Channel disabled.',
  'Job en dead-letter introuvable.': 'Dead-letter job not found.',
  'Le job sera réexécuté par le prochain worker disponible.': 'The next available worker will retry the job.',
  'Offre inconnue.': 'Unknown plan.',
  'Espace de travail introuvable.': 'Workspace not found.',
  'Un abonnement actif existe déjà. Utilisez le portail de facturation pour changer d’offre.': 'An active subscription already exists. Use the billing portal to change plan.',
  'Une souscription est déjà en cours. Réutilisez la fenêtre Stripe ouverte ou réessayez dans 30 minutes.': 'A subscription checkout is already in progress. Reuse the open Stripe window or try again in 30 minutes.',
  'Stripe n’a pas renvoyé d’URL de paiement.': 'Stripe did not return a checkout URL.',
  'Aucun client Stripe n’est associé à cet espace.': 'No Stripe customer is associated with this workspace.',
  'Aucun abonnement actif à résilier.': 'No active subscription to cancel.',
  'Abonnement introuvable.': 'Subscription not found.',
  'Cet abonnement n’est pas programmé pour résiliation.': 'This subscription is not scheduled for cancellation.',
  'Résiliation annulée. Le renouvellement reste actif.': 'Cancellation reversed. Renewal remains active.',
  'Un export est déjà en cours pour cet espace.': 'An export is already in progress for this workspace.',
  'Export demandé. Le fichier ZIP sera disponible ici après traitement.': 'Export requested. The ZIP file will be available here after processing.',
  'La suppression est déjà programmée.': 'Deletion is already scheduled.',
  'Un espace interne doit être supprimé par la procédure administrateur auditée.': 'An internal workspace must be deleted through the audited administrator procedure.',
  'La demande de suppression ne peut plus être annulée.': 'The deletion request can no longer be cancelled.',
  'Suppression annulée. Reconnectez Google Ads et recréez les clés nécessaires.': 'Deletion cancelled. Reconnect Google Ads and recreate the required keys.',
  'Demande transmise au support.': 'Request sent to support.',
  'Demande de support introuvable.': 'Support request not found.',
  'Réponse envoyée au support.': 'Reply sent to support.',
}

const englishPatterns: Array<[RegExp, (match: RegExpMatchArray) => string]> = [
  [/^(\d+) comptes synchronisés\.$/, (match) => `${match[1]} accounts synchronized.`],
  [/^(\d+) comptes synchronisés\. (\d+) compte annonceur hors quota \((.+)\) reste inactif\.$/, (match) => `${match[1]} accounts synchronized. ${match[2]} advertiser account above the quota (${match[3]}) remains inactive.`],
  [/^(\d+) signalement\(s\) détecté\(s\), (\d+) résolu\(s\)\.$/, (match) => `${match[1]} issue(s) detected, ${match[2]} resolved.`],
  [/^Approbation enregistrée \((\d+)\/(\d+)\)\.$/, (match) => `Approval recorded (${match[1]}/${match[2]}).`],
  [/^Trop de demandes\. Réessayez dans (\d+) secondes\.$/, (match) => `Too many requests. Try again in ${match[1]} seconds.`],
  [/^Trop de messages\. Réessayez dans (\d+) secondes\.$/, (match) => `Too many messages. Try again in ${match[1]} seconds.`],
  [/^Le tarif Stripe (.+) n’est pas encore configuré\.$/, (match) => `The Stripe price for ${match[1]} is not configured yet.`],
  [/^Le TXT (.+) est absent ou incorrect\.$/, (match) => `The TXT record ${match[1]} is missing or incorrect.`],
  [/^La devise de la règle doit être (.+) pour ce client\.$/, (match) => `The policy currency must be ${match[1]} for this client.`],
  [/^Résiliation enregistrée\. L’accès reste actif jusqu’au (.+)\.$/, (match) => `Cancellation scheduled. Access remains active until ${match[1]}.`],
  [/^Suppression programmée au (.+)\. Les accès et secrets ont été révoqués\.$/, (match) => `Deletion scheduled for ${match[1]}. Access and secrets have been revoked.`],
]

export function localizeFlashMessage(value: string | undefined, locale: Locale) {
  if (!value || locale === 'fr') return value
  const exact = englishMessages[value]
  if (exact) return exact
  for (const [pattern, render] of englishPatterns) {
    const match = value.match(pattern)
    if (match) return render(match)
  }
  return value
}
