import type { GettingStartedEvidence } from '@/lib/getting-started-data'
import type { AccessDecision } from '@/lib/workspace-decision'

export type GettingStartedAccess = Record<'settings' | 'google' | 'accounts' | 'goal' | 'monitor' | 'report' | 'legal', AccessDecision>

export function gettingStartedSteps(evidence: GettingStartedEvidence, access: GettingStartedAccess, english: boolean, scansEnabled: boolean) {
  const text = (fr: string, en: string) => english ? en : fr
  const blocked = (decision: AccessDecision) => decision.allowed ? null : decision.reason === 'role'
    ? text('Demandez à une personne autorisée de votre agence de réaliser cette étape.', 'Ask an authorized member of your agency to complete this step.')
    : decision.reason === 'disabled'
      ? text('Cette action est temporairement indisponible. Le support peut préciser les conditions de réouverture.', 'This action is temporarily unavailable. Support can explain the conditions for reopening it.')
      : text('L’accès actuel de l’agence ne permet pas cette action. Le propriétaire peut vérifier l’abonnement.', 'The agency’s current access does not allow this action. The owner can review the subscription.')
  const selected = Boolean(evidence.selectedClientId)
  const dashboard = evidence.selectedClientId ? `/dashboard?client=${evidence.selectedClientId}` : '/accounts'
  const steps = [
    { key: 'workspace', title: text('Organisation créée', 'Organization created'), description: text('L’espace de votre agence est disponible.', 'Your agency workspace is available.'), complete: true, href: access.settings.allowed ? '/settings' : null, action: text('Voir les réglages', 'View settings'), help: null, required: true },
    { key: 'google', title: text('Google Ads connecté', 'Google Ads connected'), description: text('La connexion enregistrée est active. Les droits Google seront vérifiés lors des collectes.', 'The stored connection is active. Google permissions are checked when data is collected.'), complete: evidence.connected, href: access.google.allowed ? '/settings' : null, action: text('Vérifier la connexion', 'Review connection'), help: blocked(access.google) ?? text('Utilisez le compte Google qui a accès aux annonceurs souhaités. Reconnectez-le si son autorisation a expiré.', 'Use the Google account that can access the advertisers you need. Reconnect it if its authorization has expired.'), required: true },
    { key: 'inventory', title: text('Premier annonceur synchronisé', 'First advertiser synchronized'), description: text('Au moins un annonceur actif est présent dans l’inventaire ; un compte manager seul ne suffit pas.', 'At least one active advertiser is in the inventory; a manager account alone does not qualify.'), complete: evidence.hasAdvertiser, href: access.google.allowed ? '/accounts' : null, action: text('Ouvrir les comptes', 'Open accounts'), help: blocked(access.google) ?? (evidence.connected ? text('Actualisez l’inventaire. Si l’annonceur manque, vérifiez ses droits dans le compte Google connecté.', 'Refresh the inventory. If an advertiser is missing, check its permissions in the connected Google account.') : text('Connectez Google Ads avant de synchroniser les annonceurs.', 'Connect Google Ads before synchronizing advertisers.')), required: true },
    { key: 'selection', title: text('Compte géré sélectionné', 'Managed account selected'), description: text('Au moins un annonceur actif est choisi pour le suivi dans les limites de votre offre.', 'At least one active advertiser is selected for monitoring within your plan limits.'), complete: selected, href: access.accounts.allowed ? '/accounts' : null, action: text('Choisir les comptes', 'Choose accounts'), help: blocked(access.accounts) ?? text('Dans les comptes clients, sélectionnez les annonceurs à gérer. La synchronisation seule ne les sélectionne pas.', 'Select the advertisers to manage in client accounts. Synchronizing them does not select them.'), required: true },
    { key: 'goal', title: text('Objectif d’un compte géré défini', 'Managed account goal defined'), description: text('Un compte sélectionné possède un objectif et un budget pour le pacing.', 'A selected account has a goal and budget for pacing.'), complete: evidence.hasGoal, href: access.goal.allowed ? dashboard : null, action: text('Définir un objectif', 'Define a goal'), help: blocked(access.goal) ?? text('Choisissez le compte dans le cockpit, puis renseignez son budget et son indicateur cible.', 'Choose the account in the cockpit, then enter its budget and target metric.'), required: true },
    { key: 'analysis', title: text('Première analyse qualifiée produite', 'First qualified analysis produced'), description: text('Une analyse a déjà été produite avec cinq sources récentes et vérifiées. Consultez la page pour leur fraîcheur actuelle.', 'An analysis has been produced with five recent, verified sources. Open the page to check their current freshness.'), complete: evidence.hasAnalysis, href: evidence.selectedClientId ? `/analysis?client=${evidence.selectedClientId}` : '/accounts', action: text('Ouvrir l’analyse', 'Open analysis'), help: text('Choisissez un compte, attendez les cinq collectes requises puis ouvrez l’analyse. Des sources anciennes ou limitées, ou des campagnes vides, ne valident pas cette étape.', 'Choose an account, wait for the five required collections, then open analysis. Stale or limited sources, or empty campaigns, do not complete this step.'), required: true },
    { key: 'monitor', title: text('Première vigie configurée', 'First monitor configured'), description: text('Une vigie est activée pour au moins un annonceur sélectionné.', 'A monitor is enabled for at least one selected advertiser.'), complete: evidence.monitorEnabled, href: access.monitor.allowed ? '/agents' : null, action: text('Configurer une vigie', 'Configure a monitor'), help: blocked(access.monitor) ?? (!scansEnabled || !evidence.connected ? text('La configuration peut être préparée ; les exécutions attendent une connexion active et la disponibilité du service de collecte et de planification.', 'Configuration can be prepared; execution requires an active connection and available collection and scheduling services.') : text('Choisissez un modèle et un seuil adapté au compte. Une vigie configurée ne prouve pas encore qu’une alerte a été reçue.', 'Choose a template and threshold suited to the account. A configured monitor does not yet prove that an alert was received.')), required: true },
    { key: 'report', title: text('Premier rapport publié', 'First report published'), description: text('Une édition a réellement été publiée. Ce jalon historique ne garantit ni la validité actuelle du lien ni une réception email.', 'An edition has actually been published. This historical milestone guarantees neither a currently valid link nor email delivery.'), complete: evidence.hasPublishedReport, href: access.report.allowed ? '/reports' : null, action: text('Ouvrir les rapports', 'Open reports'), help: blocked(access.report) ?? text('Attendez un historique qualifié pour la période demandée, puis publiez un rapport. Une programmation ou un lien sans édition ne suffit pas.', 'Wait for qualified history for the requested period, then publish a report. A schedule or a link without an edition is insufficient.'), required: true },
    { key: 'legal', title: text('Cadre commercial avant abonnement', 'Commercial terms before subscribing'), description: text('Les versions actuelles des conditions, de la confidentialité et de l’accord de traitement sont enregistrées. Cette étape commerciale est séparée du démarrage produit.', 'Current terms, privacy and data processing versions are recorded. This commercial step is separate from product setup.'), complete: evidence.legalAccepted, href: access.legal.allowed ? '/billing' : null, action: text('Consulter l’abonnement', 'Review subscription'), help: blocked(access.legal) ?? text('Le propriétaire renseigne les informations professionnelles et accepte les documents dans le parcours d’abonnement.', 'The owner enters business details and accepts the documents during subscription.'), required: false },
  ]
  const pendingDescriptions: Record<string, string> = {
    google: text('Connectez Google Ads avec un compte autorisé pour commencer les collectes.', 'Connect Google Ads with an authorized account to start collecting data.'),
    inventory: text('Synchronisez au moins un annonceur actif ; un compte manager seul ne suffit pas.', 'Synchronize at least one active advertiser; a manager account alone is insufficient.'),
    selection: text('Choisissez au moins un annonceur actif à gérer dans les limites de votre offre.', 'Choose at least one active advertiser to manage within your plan limits.'),
    goal: text('Définissez un objectif et un budget pour un compte sélectionné.', 'Set a goal and budget for a selected account.'),
    analysis: text('Ouvrez une analyse alimentée par cinq sources récentes et vérifiées pour enregistrer ce premier jalon.', 'Open an analysis backed by five recent, verified sources to record this first milestone.'),
    monitor: text('Activez une vigie applicable à au moins un annonceur sélectionné.', 'Enable a monitor that applies to at least one selected advertiser.'),
    report: text('Publiez une édition de rapport ; une programmation ou un lien sans édition ne suffit pas.', 'Publish a report edition; a schedule or a link without an edition is insufficient.'),
    legal: text('Avant l’abonnement, les versions actuelles des conditions, de la confidentialité et de l’accord de traitement devront être acceptées. Cette étape ne compte pas dans le démarrage produit.', 'Before subscribing, the current terms, privacy and data processing versions must be accepted. This step is outside product setup progress.'),
  }
  return steps.map((step) => step.complete ? step : { ...step, description: pendingDescriptions[step.key] ?? step.description })

}
