import { expect, test } from '@playwright/test'
import { randomUUID } from 'node:crypto'
import { Client } from 'pg'

if (process.env.PLAYWRIGHT_LOCAL_FIXTURE === '1') for (const [index, locale] of ['fr', 'en'].entries()) {
  test(`guided setup ${locale} requires selected accounts and qualified milestones`, async ({ browser }) => {
    const connectionString = process.env.DATABASE_SYSTEM_URL!, url = new URL(connectionString)
    if (!['localhost', '127.0.0.1', '[::1]'].includes(url.hostname) || !url.pathname.startsWith('/yodev_test')) throw new Error('Disposable database required')
    const db = new Client({ connectionString }), workspaceId = randomUUID(), organizationId = randomUUID(), clientId = randomUUID(), managerId = randomUUID()
    await db.connect()
    const original = (await db.query("select owner_user_id,auth_organization_id from workspaces where id='80000000-0000-4000-8000-000000000001'")).rows[0]
    const context = await browser.newContext({ baseURL: process.env.PLAYWRIGHT_BASE_URL, storageState: process.env.PLAYWRIGHT_OWNER_STORAGE_STATE, viewport: { width: locale === 'fr' ? 390 : 1440, height: 950 }, extraHTTPHeaders: { 'x-forwarded-for': `198.18.31.${index + 1}` } })
    await context.addCookies([{ name: 'yodev_cookie_consent', value: 'rejected', url: process.env.PLAYWRIGHT_BASE_URL! }])
    try {
      await db.query('insert into auth_organizations(id,name,slug) values($1,$2,$3)', [organizationId, 'Guided setup fixture', `guided-${organizationId}`])
      await db.query("insert into workspaces(id,auth_organization_id,owner_user_id,name,slug,plan,access_state,locale,created_at,terms_version,privacy_version) values($1,$2,$3,'Guided setup fixture',$4,'internal','internal',$5,now()-interval '1 day','2026-08-16-b2b','2026-08-16-b2b')", [workspaceId, organizationId, original.owner_user_id, `guided-${workspaceId}`, locale])
      await db.query("insert into auth_members(id,organization_id,user_id,role) values($1,$2,$3,'owner')", [randomUUID(), organizationId, original.owner_user_id])
      const active = await context.request.post('/api/auth/organization/set-active', { data: { organizationId }, headers: { origin: process.env.PLAYWRIGHT_BASE_URL! } })
      expect(active.ok()).toBe(true)
      await db.query("insert into clients(id,workspace_id,google_customer_id,name,is_manager,managed_selected) values($1,$2,'8000000080','Manager fixture',true,true)", [managerId, workspaceId])
      const page = await context.newPage(), errors: string[] = []
      page.on('pageerror', (error) => errors.push(error.message))
      const step = (key: string) => page.locator(`[data-setup-step="${key}"]`)
      await page.goto('/getting-started')
      await expect(step('inventory')).toHaveAttribute('data-complete', 'false')
      await expect(step('selection')).toHaveAttribute('data-complete', 'false')
      await expect(step('legal')).toHaveAttribute('data-complete', 'false')
      await expect(page.getByRole('progressbar', { name: /Product setup progress|Progression du démarrage produit/ })).toHaveAttribute('max', '8')
      await db.query("insert into clients(id,workspace_id,google_customer_id,name,managed_selected) values($1,$2,'8000000081','Advertiser fixture',false)", [clientId, workspaceId])
      await db.query("insert into client_goals(workspace_id,client_id,primary_kpi,monthly_budget_micros) values($1,$2,'cpa','100000000')", [workspaceId, clientId])
      await db.query("insert into monitoring_agents(workspace_id,created_by,kind,name,description,threshold,enabled) values($1,'fixture','no_delivery','Monitor fixture','Local fixture',1,true)", [workspaceId])
      await db.query("insert into share_links(workspace_id,client_id,created_by,label,token_hash,token_prefix) values($1,$2,'fixture','Unpublished fixture',$3,'fixture')", [workspaceId, clientId, randomUUID().replaceAll('-', '').padEnd(64, '0')])
      await db.query("insert into activation_milestones(workspace_id,milestone,actor_user_id,occurred_at) values($1,'first_analysis','fixture',now()),($1,'first_report','fixture',now()),($1,'first_qualified_analysis','fixture',now()+interval '1 day'),($1,'first_report_published','fixture',now()-interval '2 days')", [workspaceId])
      await page.reload()
      await expect(step('inventory')).toHaveAttribute('data-complete', 'true')
      for (const key of ['selection', 'goal', 'monitor', 'analysis', 'report']) await expect(step(key)).toHaveAttribute('data-complete', 'false')
      await db.query('update clients set managed_selected=true where id=$1', [clientId])
      await db.query("update activation_milestones set occurred_at=now() where workspace_id=$1 and milestone in ('first_qualified_analysis','first_report_published')", [workspaceId])
      await db.query("insert into legal_acceptances(workspace_id,user_id,terms_version,privacy_version,dpa_version,locale,context) values($1,'fixture','2026-08-16-b2b','2026-08-16-b2b',null,$2,'checkout_business')", [workspaceId, locale])
      await page.reload()
      for (const key of ['selection', 'goal', 'monitor', 'analysis', 'report']) await expect(step(key)).toHaveAttribute('data-complete', 'true')
      await expect(step('legal')).toHaveAttribute('data-complete', 'false')
      await db.query("update legal_acceptances set dpa_version='2026-08-16-b2b' where workspace_id=$1", [workspaceId])
      await page.reload()
      await expect(step('legal')).toHaveAttribute('data-complete', 'true')
      await expect(step('google')).toHaveAttribute('data-complete', 'false')
      await step('monitor').locator('summary').click()
      await expect(step('monitor').getByText(/exécutions attendent|execution requires/)).toBeVisible()
      await expect(page.getByRole('link', { name: /Contacter le support|Contact support/, exact: true })).toBeVisible()
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
      await page.evaluate(() => window.scrollTo(0, 0))
      await expect.poll(() => page.evaluate(() => window.scrollY)).toBe(0)
      await page.screenshot({ path: test.info().outputPath(`guided-setup-${locale}.png`), fullPage: true, caret: 'initial' })
      await db.query("update workspaces set owner_user_id='fixture-other-owner' where id=$1", [workspaceId])
      await db.query("update auth_members set role='analyst' where organization_id=$1", [organizationId])
      await page.reload()
      for (const key of ['google', 'inventory', 'selection', 'goal', 'monitor', 'legal']) await expect(step(key).getByRole('link')).toHaveCount(0)
      await step('selection').locator('summary').click()
      await expect(step('selection').getByText(/personne autorisée|authorized member/)).toBeVisible()
      await db.query("update workspaces set access_state='grace' where id=$1", [workspaceId])
      await page.reload()
      await expect(step('report')).toHaveAttribute('data-complete', 'true')
      await expect(step('report').getByRole('link')).toHaveCount(0)
      expect(errors).toEqual([])
    } finally {
      await context.close()
      await db.query('update auth_sessions set active_organization_id=$1 where active_organization_id=$2', [original.auth_organization_id, organizationId])
      await db.query('delete from workspaces where id=$1', [workspaceId])
      await db.query('delete from auth_organizations where id=$1', [organizationId])
      await db.end()
    }
  })
}
