import { expect, test } from '@playwright/test'
import { randomUUID } from 'node:crypto'
import { Client } from 'pg'

if (process.env.PLAYWRIGHT_LOCAL_FIXTURE === '1') test('operating costs preserve evidence, corrections, pagination and operator access', async ({ browser }) => {
  const connectionString = process.env.DATABASE_SYSTEM_URL!, url = new URL(connectionString)
  if (!['localhost', '127.0.0.1', '[::1]'].includes(url.hostname) || !url.pathname.startsWith('/yodev_test')) throw new Error('Disposable database required')
  const db = new Client({ connectionString }), workspaceId = '80000000-0000-4000-8000-000000000001', prefix = `browser-cost-${randomUUID()}`, sourceKey = `${prefix}-00`, month = '2001-03'
  await db.connect()
  const original = (await db.query('select access_state,plan,locale from workspaces where id=$1', [workspaceId])).rows[0]
  const context = await browser.newContext({ baseURL: process.env.PLAYWRIGHT_BASE_URL, storageState: process.env.PLAYWRIGHT_OWNER_STORAGE_STATE, viewport: { width: 1440, height: 950 }, extraHTTPHeaders: { 'x-forwarded-for': '198.18.34.1' } })
  await context.addCookies([{ name: 'yodev_cookie_consent', value: 'rejected', url: process.env.PLAYWRIGHT_BASE_URL! }])
  let reader: Awaited<ReturnType<typeof browser.newContext>> | undefined
  try {
    await db.query("update workspaces set access_state='internal',plan='internal',locale='fr' where id=$1", [workspaceId])
    const page = await context.newPage(), errors: string[] = []
    page.on('pageerror', (error) => errors.push(error.message))
    page.setDefaultTimeout(15000)
    await page.goto(`/operations/costs?month=${month}`)
    const create = page.getByRole('form', { name: 'Ajouter une observation de coût' })
    await create.getByLabel('Référence opaque du justificatif').fill(sourceKey)
    await create.getByRole('combobox', { name: 'Poste', exact: true }).selectOption('functions')
    await create.getByLabel('Montant hors taxes').fill('12.000001')
    await create.getByLabel('Méthode de répartition').selectOption('direct')
    await create.getByLabel('Solo (%)', { exact: true }).fill('100')
    await create.getByLabel('Non réparti (%)', { exact: true }).fill('0')
    await create.getByRole('button', { name: 'Enregistrer l’observation' }).click()
    await expect(page).toHaveURL(/notice=/)
    const row = page.locator('[data-cost-cell="EUR:functions:solo"]')
    await expect(row).toContainText('12.000001 EUR')
    expect((await db.query('select amount_micros,version from operating_cost_entries where source_key=$1', [sourceKey])).rows[0]).toMatchObject({ amount_micros: '12000001', version: 1 })
    const details = page.locator('details').filter({ has: page.locator('summary', { hasText: sourceKey }) })
    await details.locator('summary').click()
    const edit = page.getByRole('form', { name: `Corriger ${sourceKey}`, exact: true })
    // Simulate an independent operator correction while keeping the actual stale HTML form.
    await db.query("update operating_cost_entries set version=2,amount_micros=13000000 where source_key=$1", [sourceKey])
    await edit.getByLabel('Montant hors taxes').fill('14')
    await edit.getByRole('button').click()
    await expect(page).toHaveURL(/error=/)
    await expect(page.getByText('Cette référence a été modifiée.', { exact: false })).toBeVisible()
    await expect(row).toContainText('13.000000 EUR')
    await details.locator('summary').click()
    await edit.getByLabel('Montant hors taxes').fill('14')
    await edit.getByRole('button').click()
    await expect(page).toHaveURL(/notice=/)
    await expect(row).toContainText('14.000000 EUR')
    // Another 30 rows exceed page size; monthly totals must include the last one.
    await db.query("insert into operating_cost_entries(source_key,month,category,currency,basis,amount_micros,allocation_method,updated_by) select $1||'-'||lpad(i::text,2,'0'),$2,'storage','USD','estimated',1000000,'unallocated','browser-fixture' from generate_series(1,30) i", [prefix, month])
    await page.reload()
    await expect(page.locator('[data-cost-cell="USD:storage:unallocated"]')).toContainText('30.000000 USD')
    await expect(page.locator('form[aria-label^="Corriger " ]')).toHaveCount(25)
    await page.getByRole('link', { name: 'Page suivante', exact: true }).click()
    await expect(page.locator('form[aria-label^="Corriger " ]')).toHaveCount(6)
    await expect(page.locator('[data-cost-cell="USD:storage:unallocated"]')).toContainText('30.000000 USD')
    await page.getByRole('link', { name: 'Première page', exact: true }).click()
    await details.locator('summary').click()
    await edit.getByLabel('Prise en compte').selectOption('true')
    await edit.getByRole('button').click()
    await expect(page).toHaveURL(/notice=/)
    await expect(row).toHaveCount(0)
    expect((await db.query("select count(*)::int as count from audit_events where action='operations.cost_recorded' and entity_id=(select id::text from operating_cost_entries where source_key=$1)", [sourceKey])).rows[0].count).toBe(3)
    await page.evaluate(() => window.scrollTo(0, 0))
    await page.screenshot({ path: test.info().outputPath('operating-costs-desktop.png'), fullPage: true, caret: 'initial' })
    await page.setViewportSize({ width: 390, height: 950 })
    const region = page.getByRole('region', { name: 'Coûts par offre et par poste', exact: true })
    await region.focus(); await page.keyboard.press('ArrowRight')
    await expect.poll(() => region.evaluate((element) => element.scrollLeft)).toBeGreaterThan(0)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await page.evaluate(() => window.scrollTo(0, 0))
    await page.screenshot({ path: test.info().outputPath('operating-costs-mobile.png'), fullPage: true, caret: 'initial' })
    reader = await browser.newContext({ baseURL: process.env.PLAYWRIGHT_BASE_URL, storageState: process.env.PLAYWRIGHT_ANALYST_STORAGE_STATE, extraHTTPHeaders: { 'x-forwarded-for': '198.18.34.2' } })
    const restricted = await reader.newPage()
    expect((await restricted.goto(`/operations/costs?month=${month}`))?.status()).toBe(404)
    expect((await restricted.goto('/operations'))?.status()).toBe(404)
    await expect(restricted.getByRole('heading', { name: 'Coûts par offre', exact: true })).toHaveCount(0)
    await db.query("update workspaces set access_state='active',plan='agency' where id=$1", [workspaceId])
    await page.goto(`/operations/costs?month=${month}`)
    await expect(page.getByRole('heading', { name: 'Coûts par offre', exact: true })).toHaveCount(0)
    expect(errors).toEqual([])
  } finally {
    await reader?.close().catch(() => {}); await context.close().catch(() => {})
    await db.query("delete from audit_events where action='operations.cost_recorded' and entity_id in (select id::text from operating_cost_entries where source_key like $1)", [`${prefix}-%`])
    await db.query('delete from operating_cost_entries where source_key like $1', [`${prefix}-%`])
    await db.query('update workspaces set access_state=$1,plan=$2,locale=$3 where id=$4', [original.access_state, original.plan, original.locale, workspaceId])
    await db.end()
  }
})
